--q1

CREATE TABLE CITIES (
LOCATION_ID NUMBER(4),
STREET_ADDRESS VARCHAR2(40),
POSTAL_CODE VARCHAR2(12),
CITY VARCHAR2(30) NOT NULL,
STATE_PROVINCE VARCHAR2(25),
COUNTRY_ID CHAR(2)
);

INSERT INTO CITIES(
select LOCATION_ID, STREET_ADDRESS, POSTAL_CODE,
CITY, STATE_PROVINCE, COUNTRY_ID
from LOCATIONS
where LOCATION_ID < 2000);

--Q2

CREATE TABLE TOWNS (
LOCATION_ID number(4),
STREET_ADDRESS varchar2(40),
POSTAL_CODE varchar2(12),
CITY varchar2(30) not null,
STATE_PROVINCE varchar2(25),
COUNTRY_ID char(2)
);

INSERT INTO TOWNS(
select LOCATION_ID, STREET_ADDRESS, POSTAL_CODE,
CITY, STATE_PROVINCE, COUNTRY_ID
from LOCATIONS
where LOCATION_ID < 1500);

--Q3)

PURGE RECYCLEBIN;

SELECT * FROM RECYCLEBIN;

DROP TABLE TOWNS;

SELECT * FROM RECYCLEBIN;

--Q4)

flashback table TOWNS to before drop;

DESC TOWNS;

select * from RECYCLEBIN;

--q5)

DROP TABLE TOWNS PURGE;

SELECT TOWNS, 2017-08-01:22:02:04 
FROM RECYCLEBIN;

flashback table TOWNS to before drop;

--q6)

CREATE VIEW CAN_CITY_VU as (
select STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE
from CITIES
where COUNTRY_ID = 'CA');

SELECT * FROM CAN_CITY_VU;

--q7)

CREATE OR REPLACE VIEW CAN_CITY_VU AS (
SELECT STREET_ADDRESS AS "Str_Adr", POSTAL_CODE AS "P_Code", CITY AS "City", STATE_PROVINCE AS "Prov"
FROM CITIES
WHERE COUNTRY_ID IN ('IT', 'CA'));

--q8)

CREATE VIEW CITY_DNAME_VU as (
  select dept.DEPARTMENT_NAME, loc.CITY, loc.STATE_PROVINCE
  from DEPARTMENTS dept
  full outer join LOCATIONS loc
  on dept.LOCATION_ID = loc.LOCATION_ID
  where loc.COUNTRY_ID IN ('IT', 'CA')
);

SELECT * FROM CITY_DNAME_VU;

--q9)

create or replace view CITY_DNAME_VU as (
  select dept.DEPARTMENT_NAME as "dname", loc.CITY as "city", loc.STATE_PROVINCE as "prov"
  from DEPARTMENTS dept
  full outer join LOCATIONS loc
  on dept.LOCATION_ID = loc.LOCATION_ID
  where loc.COUNTRY_ID NOT IN ('US')
);

SELECT * FROM CITY_DNAME_VU;

--Q10)

select view_name from user_views;

drop view CITY_DNAME_VU;

select view_name from user_views;
